mysql:
  host: 'localhost'
  port: 3306
  database: 'reputation'
  args: '?autoReconnect=true'
  user: 'root'
  password: ''

settings:
  auto-update-reputation: true

message:
  no-permissions: '&cВам недоступна эта команда!'
  help: '&a/admrep reload &f- перезагрузить плагин\n&a/admrep <give/take> <ник> <кол-во> &f- выдать/забрать репутацию у игрока'
  not-number: '&cОжидалось число на месте ''%command-arg2%'''
  target-not-found: '&cТакой игрок не найден!'
  added-to-target: '&fИгроку &a%target-name%&f было выдано &a%command-arg2%&f очков репутации! Общий счёт: &a%target-rep%'
  removed-from-target: '&fУ игрока &c%target-name%&f было забрано &c%command-arg2%&f очков репутации! Общий счёт: &c%target-rep%'