name: Reputation
version: ${project.version}
main: ru.ibusewinner.reputation.Reputation
api-version: 1.13
description: Mega Reputation plugin
website: https://spigotmc.ru/resources/124/
softdepend: [PlaceholderAPI]

commands:
  adminreputation:
    aliases: [adminrep,admrep]