name: Reputation
version: '3.0.9-БЕТА'
main: ru.fennec.free.reputation.ReputationPlugin
#api-version: 1.19
softdepend: [ PlaceholderAPI ]
authors: [ BuseSo ]
description: Система репутации как социальный рейтинг в Китае
website: https://spigotmc.ru/members/307/

commands:
  reputation:
    description: Главная команда плагина
    aliases: [rep,fenrep,buserep]
